# generated by tools/tfdocs; delete this line to maintain the example by hand
resource "netskopebwan_controller_operator" "example" {
  default      = false
  display_name = "example"
  identity     = "<identity>"
  public_ipv4  = "<public_ipv4>"
}
