# generated by tools/tfdocs; delete this line to maintain the example by hand
resource "netskopebwan_address_object" "example" {
  address  = "<address>"
  group_id = "6501f0c2e4b0a1b2c3d4e5f6"
  name     = "example"
  type     = "ipv4"
}
