# generated by tools/tfdocs; delete this line to maintain the example by hand
# Every page is walked, so data holds the whole collection and total_count is
# what the API reports for it. A filter narrows the list; sort orders it.
data "netskopebwan_tags_overlay" "example" {
  filter = "name eq \"example\""
}
