# generated by tools/tfdocs; delete this line to maintain the example by hand
resource "netskopebwan_cloud_account" "example" {
  cloud_provider = "aws"
  config = {
    aws = {
      key_id            = "<key_id>"
      secret_access_key = "<secret_access_key>"
    }
  }
  name = "example"
}
