# generated by tools/tfdocs; delete this line to maintain the example by hand
resource "netskopebwan_controller" "example" {
  operator_nrn = "<operator_nrn>"
  public_ipv4  = "<public_ipv4>"
  version      = "<version>"
}
