name: Release Terraform Provider

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Import GPG key
        uses: infiotinc/ghaction-import-gpg@92a10f995fd20944e1cae9a2e86e62dafe4f6171
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      # - name: Import GPG key
      #   env:
      #     GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      #     GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}
      #   run: |
      #     echo "$GPG_PRIVATE_KEY" | gpg --batch --import
      #     GPG_FINGERPRINT=$(gpg --list-secret-keys --keyid-format long | grep sec | head -1 | awk '{print $2}' | cut -d'/' -f2)
      #     echo "GPG_FINGERPRINT=$GPG_FINGERPRINT" >> "$GITHUB_ENV"
      - name: Install GoReleaser
        run: go install github.com/goreleaser/goreleaser/v2@latest
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

          # GPG_FINGERPRINT: ${{ env.GPG_FINGERPRINT }}
          # GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          # GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          goreleaser release --clean